name: ai_resume_tracker
description: "AI Resume Tracker"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  get_it: ^8.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5

  custom_design_system:
    path: ../custom_design_system

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
